import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Palette, Type, Check, RefreshCw } from 'lucide-react';
import toast from 'react-hot-toast';
export const Settings = ({ borderColor, headerColor, onBorderColorChange, onHeaderColorChange, darkMode = false }) => {
    const presetPalettes = [
        { name: 'Slate Ejecutivo', header: '#0f172a', border: '#e2e8f0' },
        { name: 'Azul Corporativo', header: '#1e40af', border: '#cbd5e1' },
        { name: 'Negro Monocromo', header: '#18181b', border: '#e4e4e7' },
        { name: 'Azul Acero', header: '#1e293b', border: '#cbd5e1' },
        { name: 'Verde Esmeralda', header: '#065f46', border: '#a7f3d0' },
        { name: 'Púrpura Luxe', header: '#4c1d95', border: '#ddd6fe' }
    ];
    return (_jsx("div", { className: "space-y-8", children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8 items-start", children: [_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-3", children: "Paletas Recomendadas de Marca" }), _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-3 gap-2.5", children: presetPalettes.map((palette) => {
                                        const isActive = headerColor === palette.header && borderColor === palette.border;
                                        return (_jsxs("button", { onClick: () => {
                                                onHeaderColorChange(palette.header);
                                                onBorderColorChange(palette.border);
                                                toast.success(`Paleta "${palette.name}" aplicada`);
                                            }, className: `p-3 rounded-xl border text-left flex flex-col justify-between transition-all ${isActive
                                                ? 'border-blue-600 ring-2 ring-blue-500/30 bg-blue-500/10'
                                                : darkMode
                                                    ? 'border-slate-800 bg-slate-900 hover:border-slate-700'
                                                    : 'border-slate-200 bg-slate-50 hover:border-slate-300'}`, children: [_jsx("span", { className: "text-xs font-bold truncate mb-2", children: palette.name }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("div", { className: "w-5 h-5 rounded-md border border-white/20 shadow-sm", style: { backgroundColor: palette.header } }), _jsx("div", { className: "w-5 h-5 rounded-md border border-slate-300 shadow-sm", style: { backgroundColor: palette.border } }), isActive && _jsx(Check, { className: "w-4 h-4 text-blue-500 ml-auto" })] })] }, palette.name));
                                    }) })] }), _jsxs("div", { className: `p-5 rounded-2xl border ${darkMode ? 'bg-slate-900 border-slate-800' : 'bg-slate-50 border-slate-200'}`, children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx(Type, { className: "w-4 h-4 text-blue-500" }), _jsx("label", { className: "text-xs font-bold uppercase tracking-wider", children: "Color de Encabezado / Primario" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("input", { type: "color", value: headerColor, onChange: (e) => onHeaderColorChange(e.target.value), className: "w-12 h-12 rounded-xl cursor-pointer border-0 p-0 bg-transparent shrink-0" }), _jsx("input", { type: "text", value: headerColor, onChange: (e) => onHeaderColorChange(e.target.value), className: `flex-1 px-4 py-2 text-xs font-mono font-bold uppercase border rounded-xl ${darkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'}`, placeholder: "#0f172a" })] })] }), _jsxs("div", { className: `p-5 rounded-2xl border ${darkMode ? 'bg-slate-900 border-slate-800' : 'bg-slate-50 border-slate-200'}`, children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx(Palette, { className: "w-4 h-4 text-indigo-500" }), _jsx("label", { className: "text-xs font-bold uppercase tracking-wider", children: "Color de Bordes & Divisores" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("input", { type: "color", value: borderColor, onChange: (e) => onBorderColorChange(e.target.value), className: "w-12 h-12 rounded-xl cursor-pointer border-0 p-0 bg-transparent shrink-0" }), _jsx("input", { type: "text", value: borderColor, onChange: (e) => onBorderColorChange(e.target.value), className: `flex-1 px-4 py-2 text-xs font-mono font-bold uppercase border rounded-xl ${darkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'}`, placeholder: "#e2e8f0" })] })] }), _jsxs("button", { onClick: () => {
                                onHeaderColorChange('#0f172a');
                                onBorderColorChange('#e2e8f0');
                                toast.success('Valores predeterminados restaurados');
                            }, className: "flex items-center justify-center gap-2 w-full px-4 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 text-xs font-bold text-slate-500 hover:text-slate-900 dark:hover:text-white transition-colors", children: [_jsx(RefreshCw, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "Restaurar Valores Predeterminados" })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("label", { className: "block text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider", children: "Vista Previa de Colores de Marca" }), _jsxs("div", { className: "bg-white p-6 rounded-2xl shadow-xl text-slate-900 font-sans space-y-5", style: { border: `1px solid ${borderColor}` }, children: [_jsxs("div", { className: "flex justify-between items-center pb-4 border-b", style: { borderColor }, children: [_jsxs("div", { children: [_jsx("h4", { className: "font-extrabold text-base", children: "MI EMPRESA, S.A." }), _jsx("p", { className: "text-xs text-slate-500 font-mono", children: "NIT: 12345678-9" })] }), _jsxs("div", { className: "px-3 py-2 rounded-xl text-white text-right font-mono text-xs font-bold", style: { backgroundColor: headerColor }, children: [_jsx("p", { children: "FACTURA FEL" }), _jsx("p", { className: "text-[10px] opacity-80", children: "A-0012345" })] })] }), _jsxs("table", { className: "w-full text-xs text-left border-collapse", children: [_jsx("thead", { children: _jsxs("tr", { className: "text-white text-[10px] uppercase font-bold", style: { backgroundColor: headerColor }, children: [_jsx("th", { className: "py-2 px-3", children: "\u00CDtem" }), _jsx("th", { className: "py-2 px-3 text-right", children: "Total" })] }) }), _jsx("tbody", { className: "divide-y", style: { borderColor }, children: _jsxs("tr", { children: [_jsx("td", { className: "py-2 px-3 font-medium", children: "Servicios Profesionales FEL" }), _jsx("td", { className: "py-2 px-3 text-right font-mono font-bold", children: "Q 150.00" })] }) })] }), _jsxs("div", { className: "p-3 rounded-xl text-white text-right space-y-0.5", style: { backgroundColor: headerColor }, children: [_jsx("span", { className: "text-[10px] uppercase tracking-wider block opacity-80", children: "Total General" }), _jsx("span", { className: "text-xl font-black font-mono", children: "Q 150.00" })] })] })] })] }) }));
};
