import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Sidebar } from './Sidebar';
import { Upload, Sparkles, FileCheck } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
export const MainLayout = ({ activeTab, setActiveTab, darkMode, setDarkMode, onOpenPricing, onNewXmlClick, invoiceCount = 0, invoiceLimit = 10, children }) => {
    const [collapsed, setCollapsed] = useState(false);
    const { userData } = useAuth();
    return (_jsxs("div", { className: `min-h-screen flex font-sans ${darkMode ? 'dark bg-slate-950 text-slate-100' : 'bg-slate-50 text-slate-900'}`, children: [_jsx("div", { className: "print:hidden", children: _jsx(Sidebar, { activeTab: activeTab, setActiveTab: setActiveTab, collapsed: collapsed, setCollapsed: setCollapsed, darkMode: darkMode, setDarkMode: setDarkMode, onOpenPricing: onOpenPricing, invoiceCount: invoiceCount, invoiceLimit: invoiceLimit }) }), _jsxs("div", { className: "flex-1 flex flex-col min-w-0 overflow-hidden", children: [_jsxs("header", { className: `
          h-16 px-6 flex items-center justify-between border-b select-none transition-colors print:hidden
          ${darkMode ? 'bg-slate-900/80 border-slate-800 backdrop-blur-md' : 'bg-white/80 border-slate-200 backdrop-blur-md'}
        `, children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("h1", { className: "text-lg font-extrabold tracking-tight capitalize flex items-center gap-2", children: [activeTab === 'dashboard' && (_jsxs(_Fragment, { children: [_jsx(FileCheck, { className: "w-5 h-5 text-blue-500" }), _jsx("span", { children: "Visualizador FEL Guatemala" })] })), activeTab === 'history' && _jsx("span", { children: "Historial de Facturas" }), activeTab === 'settings' && _jsx("span", { children: "Configuraci\u00F3n de Marca" }), activeTab === 'pricing' && _jsx("span", { children: "Planes y Suscripci\u00F3n" }), activeTab === 'admin' && _jsx("span", { children: "Panel Administrador" })] }), _jsx("span", { className: "hidden sm:inline-block px-2.5 py-0.5 text-xs font-semibold rounded-full bg-blue-500/10 text-blue-600 dark:text-blue-400 border border-blue-500/20", children: "SAT FEL v1.3" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [activeTab !== 'dashboard' && onNewXmlClick && (_jsxs("button", { onClick: () => {
                                            setActiveTab('dashboard');
                                            onNewXmlClick();
                                        }, className: "hidden sm:flex items-center gap-2 px-3.5 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-medium text-xs shadow-md shadow-blue-600/20 transition-all hover:scale-105 active:scale-95", children: [_jsx(Upload, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "Cargar XML FEL" })] })), userData?.plan === 'free' && (_jsxs("button", { onClick: onOpenPricing, className: "flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-white font-bold text-xs shadow-md shadow-amber-500/20 transition-transform hover:scale-105", children: [_jsx(Sparkles, { className: "w-3.5 h-3.5 fill-white/30" }), _jsx("span", { className: "hidden md:inline", children: "Obtener Plan PRO" }), _jsx("span", { className: "md:hidden", children: "PRO" })] }))] })] }), _jsx("main", { className: "flex-1 overflow-y-auto p-4 sm:p-6 md:p-8", children: _jsx("div", { className: "max-w-7xl mx-auto space-y-6", children: children }) })] })] }));
};
